# Generated by Django 6.0.4 on 2026-06-22 16:39

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='tag_color',
            field=models.CharField(blank=True, help_text='Hex color code from form', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status_code',
            field=app.models.UpperCaseCharField(help_text='Will be saved in uppercase', max_length=20),
        ),
    ]
