import asyncio
import logging
import os
from typing import Final

import ollama
from aiogram import Bot, Dispatcher, F, types
from aiogram.filters import Command
from dotenv import load_dotenv


load_dotenv()

BOT_TOKEN: Final[str] = os.getenv("BOT_TOKEN", "")
MODEL_NAME: Final[str] = os.getenv("OLLAMA_MODEL", "llama3")
MAX_DIALOGUE_MESSAGES: Final[int] = 6
MAX_TELEGRAM_MESSAGE_LENGTH: Final[int] = 4096

SYSTEM_PROMPT: Final[str] = """
Ти — саркастичний робот-помічник із 2115 року. Ти любиш жартувати над сучасними технологіями, але водночас допомагаєш користувачу. Твої відповіді мають бути короткими, дотепними та містити трохи кіберпанк-сленгу.
"""

if not BOT_TOKEN:
    raise RuntimeError("Не знайдено BOT_TOKEN. Додайте його до файлу .env.")

bot = Bot(token=BOT_TOKEN)
dp = Dispatcher()
ollama_client = ollama.AsyncClient()

user_memory: dict[int, list[dict[str, str]]] = {}


def get_user_history(user_id: int) -> list[dict[str, str]]:
    """
    Returns an existing dialogue history or creates a new one for a user.
    :param user_id: Telegram identifier of the user
    :return: list of messages for the LLM conversation
    """
    if user_id not in user_memory:
        user_memory[user_id] = [{"role": "system", "content": SYSTEM_PROMPT}]
    return user_memory[user_id]


def trim_history(history: list[dict[str, str]]) -> None:
    """
    Keeps the system prompt and recent messages to limit the LLM context.
    :param history: list of messages in the current dialogue
    :return: nothing
    """
    if len(history) > MAX_DIALOGUE_MESSAGES + 1:
        history[:] = [history[0], *history[-MAX_DIALOGUE_MESSAGES:]]


def split_for_telegram(text: str) -> list[str]:
    """
    Splits a long response into parts accepted by Telegram.
    :param text: response text generated by the LLM
    :return: list of text parts no longer than Telegram's limit
    """
    return [
        text[index : index + MAX_TELEGRAM_MESSAGE_LENGTH]
        for index in range(0, len(text), MAX_TELEGRAM_MESSAGE_LENGTH)
    ] or ["Відповідь моделі порожня."]


@dp.message(Command("start"))
async def command_start(message: types.Message) -> None:
    """
    Sends a greeting after the /start command.
    :param message: incoming Telegram message
    :return: nothing
    """
    await message.answer(
        "Вітаю Вас, щось хочете сказати?"
    )


@dp.message(F.text)
async def chat_with_ai(message: types.Message) -> None:
    """
    Sends a user's text to Llama 3 and replies in Telegram.
    :param message: incoming Telegram message with text
    :return: nothing
    """
    if message.from_user is None or message.text is None:
        return

    history = get_user_history(message.from_user.id)
    history.append({"role": "user", "content": message.text})
    trim_history(history)

    try:
        response = await ollama_client.chat(model=MODEL_NAME, messages=history)
        bot_reply = response.message.content.strip()

        if not bot_reply:
            bot_reply = "Тиша."

        history.append({"role": "assistant", "content": bot_reply})
        trim_history(history)

        for part in split_for_telegram(bot_reply):
            await message.answer(part)
    except ollama.ResponseError as error:
        logging.exception("Помилка відповіді Ollama: %s", error)
        await message.answer(
            "Немає зв'язку з ollama."
        )
    except Exception:
        logging.exception("Помилка під час обробки повідомлення.")
        await message.answer("Будь ласка, зачекайте..")


async def main() -> None:
    """
    Starts the Telegram bot with long polling.
    :return: nothing
    """
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
    )
    logging.info("Бот запущено. Модель Ollama: %s", MODEL_NAME)
    await dp.start_polling(bot)


if __name__ == "__main__":
    asyncio.run(main())
